# This file was generated by GoReleaser. DO NOT EDIT.
cask "leetgo" do
  name "leetgo"
  desc "leetgo is a command line tool for leetcode.com. It can help you to login, submit, test, and view your submissions."
  homepage "https://github.com/javenlee99/leetgo"
  version "1.4.11-custom"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "leetgo"
  bash_completion "completions/leetgo.bash"
  zsh_completion "completions/leetgo.zsh"
  fish_completion "completions/leetgo.fish"

  on_macos do
    on_intel do
      url "https://github.com/javenlee99/leetgo/releases/download/v#{version}/leetgo_macOS_x86_64.tar.gz"
      sha256 "51178b077f9da357e4a288301a1f55dd1361cac737bf7f0aedc49094c42b1ed3"
    end
    on_arm do
      url "https://github.com/javenlee99/leetgo/releases/download/v#{version}/leetgo_macOS_arm64.tar.gz"
      sha256 "479c8f1e95ea69ac3f694ec41e5ad7fb8aa67e8aa7934b075705e24c98b734d0"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/javenlee99/leetgo/releases/download/v#{version}/leetgo_linux_x86_64.tar.gz"
      sha256 "568e86db2f4284d986289741ffa6e5c7a34b65e9fed1f879e5ba2614536940cf"
    end
    on_arm do
      url "https://github.com/javenlee99/leetgo/releases/download/v#{version}/leetgo_linux_arm64.tar.gz"
      sha256 "3878f5cce6d3c0ec736fe04e58bb14118ab175af025b9cb1c2f4c8704a4ebb06"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/leetgo"]
    end
  end

  # No zap stanza required
end
