# This file was generated by GoReleaser. DO NOT EDIT.
cask "leetgo" do
  name "leetgo"
  desc "leetgo is a command line tool for leetcode.com. It can help you to login, submit, test, and view your submissions."
  homepage "https://github.com/javenlee99/leetgo"
  version "1.4.15-custom"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "leetgo"
  bash_completion "completions/leetgo.bash"
  zsh_completion "completions/leetgo.zsh"
  fish_completion "completions/leetgo.fish"

  on_macos do
    on_intel do
      url "https://github.com/javenlee99/leetgo/releases/download/v#{version}/leetgo_macOS_x86_64.tar.gz"
      sha256 "b9d1ef3130764edd100741e912a8ae9c4874249e1432c03f1e6f71e69c40a364"
    end
    on_arm do
      url "https://github.com/javenlee99/leetgo/releases/download/v#{version}/leetgo_macOS_arm64.tar.gz"
      sha256 "1f682c5817826d1f3d687b1aaf7f7e94e81347db24e488f0c3fbca0ef76aad12"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/javenlee99/leetgo/releases/download/v#{version}/leetgo_linux_x86_64.tar.gz"
      sha256 "b9477356bdb3d5c8386ac84bb772c46c768f758136ea3e572f697e26082f14ad"
    end
    on_arm do
      url "https://github.com/javenlee99/leetgo/releases/download/v#{version}/leetgo_linux_arm64.tar.gz"
      sha256 "cf930b5b3cca84781e82a94d2b15209f1fa86af27c23d04147e45f8685aa25ed"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/leetgo"]
    end
  end

  # No zap stanza required
end
