# This file was generated by GoReleaser. DO NOT EDIT.
cask "leetgo" do
  name "leetgo"
  desc "leetgo is a command line tool for leetcode.com. It can help you to login, submit, test, and view your submissions."
  homepage "https://github.com/javenlee99/leetgo"
  version "1.4.14-custom"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "leetgo"
  bash_completion "completions/leetgo.bash"
  zsh_completion "completions/leetgo.zsh"
  fish_completion "completions/leetgo.fish"

  on_macos do
    on_intel do
      url "https://github.com/javenlee99/leetgo/releases/download/v#{version}/leetgo_macOS_x86_64.tar.gz"
      sha256 "3dcf25de57ebb6857038387e86756de739b3d03261659f32b7ad8cc5fc2e62e9"
    end
    on_arm do
      url "https://github.com/javenlee99/leetgo/releases/download/v#{version}/leetgo_macOS_arm64.tar.gz"
      sha256 "0f3917894ce111be589031a848a03ee37076c7a0522f40db67fd63de11fa4c9a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/javenlee99/leetgo/releases/download/v#{version}/leetgo_linux_x86_64.tar.gz"
      sha256 "868357e07fe36568b67a6af460224488e3d6ad4db9c9cb9253fb772267856a7b"
    end
    on_arm do
      url "https://github.com/javenlee99/leetgo/releases/download/v#{version}/leetgo_linux_arm64.tar.gz"
      sha256 "8e6e7783d1e94581f9d4b194823516e3e11a57c34087e145c4cdb72000bc4d25"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/leetgo"]
    end
  end

  # No zap stanza required
end
